# Generated by Django 5.0.3 on 2024-03-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_dir', models.BooleanField(default=False)),
                ('filepath', models.CharField(max_length=200)),
                ('path_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.pathmap')),
            ],
        ),
    ]
