# Generated by Django 5.0.3 on 2024-04-02 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
