# Generated by Django 5.0.3 on 2024-04-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_storageitem_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='filepath',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
