# Generated by Django 5.0.3 on 2024-04-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_alter_storageitem_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='filepath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
