# Generated by Django 5.0.3 on 2024-04-02 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_alter_storageitem_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageitem',
            name='path_id',
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.folder')),
            ],
        ),
        migrations.DeleteModel(
            name='PathMap',
        ),
        migrations.DeleteModel(
            name='StorageItem',
        ),
    ]
