# Generated by Django 5.0.8 on 2025-01-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedrive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shared_users',
        ),
        migrations.AlterField(
            model_name='item',
            name='is_empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filedrive.item'),
        ),
    ]
