# Generated by Django 5.0.8 on 2025-02-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedrive', '0002_remove_item_shared_users_alter_item_is_empty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_empty',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
