# Generated by Django 5.0.8 on 2025-02-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedrive', '0003_remove_item_is_empty_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='object_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
