on:
  pull_request:
    branches:
    - main
    types: [opened, synchronize, reopened]
name: CI
jobs:
  E2E-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Super-Linter
      uses: super-linter/super-linter@v6.3.1
    
