on:
  pull_request:
    branches:
    - main
    types: [opened, synchronize, reopened]
name: Static Code Analysis
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Super-Linter
      uses: super-linter/super-linter/slim@v6.3.1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       VALIDATE_ALL_CODEBASE: false
       DEFAULT_BRANCH: main
       VALIDATE_JAVASCRIPT_ES: true
       VALIDATE_PYTHON: true
       
