on:
  pull_request:
    branches:
    - main
    types: [opened, synchronize, reopened]
name: CI
jobs:
  E2E-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: E2E Tests  
      uses: cypress-io/github-action@v6
    
